### ISSUE TITLE
File Uploading Endpoint doesn't work

### ISSUE THREAD

**Issue by sunsetjesus** [Kohze/RelysiaSDK#1]
### Sample code

`            let uploadThumbnail = await relysia.upload({
                                body : {
                                    type: "media",
                                    fileUrl: "https://firebasestorage.googleapis.com/v0/b/musicartdev/o/nftAssets%2F0bb0267f-d5e4-4266-9499-987e2c910451_250x250?alt=media",
                                    fileName: "thumbnail",
                                    notes: "Nft Thumbnail"
                                }
                               })`
                              
  **Returns 402**

**Comment by Adityapanther** [comment]
@sunsetjesus please share error message screenshot on aditya@vaionex.com


CC @manoj-vaionex
