### ISSUE TITLE
Missing inputs when use params like doc， it works yesterday

### ISSUE THREAD

**Issue by GHChrisSu** [Kohze/RelysiaSDK#2]
I was testing code like below

![image](https://user-images.githubusercontent.com/13779988/186054304-d68b3691-09ef-4225-a833-445ca55552da.png)

And I got missing input error,  status code 400

![image](https://user-images.githubusercontent.com/13779988/186054141-088f2427-a8ae-4c9f-84f9-b30ba259f839.png)

**Comment by Adityapanther** [comment]
@GHChrisSu please share your userId or email on aditya@vaionex.com, so I can help you with this issue

**Comment by GHChrisSu** [comment]
My email is suhao@chainbow.io, it should be the utxos not be confirmed caused this.

**Comment by Adityapanther** [comment]
@GHChrisSu your issue has been fixed now, please verify and let us know
